version: 0.2

phases:
  pre_build:
    commands:
      - dockerLoginCmd=$(aws ecr get-login --no-include-email --region us-east-1)
      - eval $dockerLoginCmd
  build:
    commands:
      - docker build -t alpine:latest .
  post_build:
    commands:
      - docker tag docker-beta-mac-ruby:latest 449325314696.dkr.ecr.us-east-1.amazonaws.com/alpine:latest
      - docker push 449325314696.dkr.ecr.us-east-1.amazonaws.com/alpine:latest
